### PR TITLE
completed typescript-timers -Andrew Owyang

### PR DESCRIPTION
**Pull request by Ajowyang**
Recording 2024-08-05 at 11 03 46

### CODE REVIEW

**Review by brandon-moy — CHANGES_REQUESTED** [review]
In your `interval.ts`, you shouldn't rely on the `textContent` property of your DOM element and manipulate that in order to determine your count. Instead you should be using a variable for this. It keeps the data in your TypeScript/JavaScript rather than just to do a lot of type/variable manipulation to get the value.

Also - quiz question answers!

**Comment by Ajowyang** [comment]
Recording 2024-08-05 at 11 20 29 (2)

**Review by brandon-moy — CHANGES_REQUESTED** [review]
You are still using the `textContent` property to determine what count you are on and modifying it. You can just use a variable with a value of 4 to start, calculate and decrement that, and that will make all of this much simpler than all of the conversions and checks you are running inside of your callback function.

**Review by brandon-moy — APPROVED** [review]
👍

**Pull request merged**
